const words = ['JavaScript',
               'Java', 
               'Ruby',
               'Python',
               'Pascal',
               'Fortran',
               'Cobol',
               'React',
               'Angular',
               'Express ',
               'Svelte',
               'Laravel',
               'Symfony',
               'CodeIgniter',
               'CakePHP',
               'Django',
               'Spring',
               'Postgres',
               'Mongodb',
               'Informix'];